### ISSUE TITLE
Concurrency 2.0

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1724]
This ticket is a summary of the tasks that we should take to improve our concurrency support.

- [ ] Add nursery-based concurrency (see #797). The idea is that to spawn a light-weight process you must have a nursery object ("capability"). A nursery object is scoped and acts as an implicit join point, i.e. when the nursery goes out of scope all threads spawned by it must have finished.
- [ ] Add a scoped-let construct see (#1371) (for dealing with the nursery). 
- [ ] Allow channel creation with a size argument (see #784).
- [x] Allow wildcard in select (see #768).
- [ ] Runtime: Cleanup select listeners (see #1719) to prevent memory leaks.
- [x] Runtime: Use Random probing to prevent starvation (see #1718).
- [x] Runtime: Unlock in reverse order (#1730).
- [ ] Redesign channel syntax (see #1479) (see also #1169)
- [ ] Figure out how to handle thread death (see #744).
- [ ] Use VirtualThreads - needs to wait for Java 17 or whatever (see https://github.com/flix/flix/issues/1130).
- [ ] Allow channel put operations in select (https://github.com/flix/flix/issues/1735).
- [ ] Only allow immutable/`Send` values to be sent on channels? (no ticket?)
- [ ] Split channel into `Sender` and `Receiver`? (no ticket?)
- [ ] Add some useful APIs (see e.g. Crossbeam from Rust) (https://docs.rs/crossbeam/0.8.0/crossbeam/).
- [ ] When everything is ready: Add examples and tests (see #724).
- [ ] Reimplement `Channel.java` in Flix (#1840)
- [ ] Benchmark and compare to https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel/benchmarks (#1841)
- [ ] Should channels also be scoped by the nursery?

(The above list is in no specific order.)

**Comment by justinfargnoli** [comment]
I created ticket #1730 for, "Runtime: Unlock in reverse order (no ticket)."

**Comment by justinfargnoli** [comment]
I created ticket #1840 for, "Reimplement Channel.java in Flix"

**Comment by justinfargnoli** [comment]
I created ticket #1841 for, "Benchmark and compare to https://github.com/crossbeam-rs/crossbeam/tree/master/crossbeam-channel/benchmarks"

**Comment by magnus-madsen** [comment]
Thanks! I updated the TODO list.

**Comment by JonathanStarup** [comment]
@magnus-madsen maybe this should be updated and then we can close #2169 - the only things missing are concurrency things listed here (except channel lowering).

**Comment by magnus-madsen** [comment]
Continued in https://github.com/flix/flix/issues/4755.
