### ISSUE TITLE
Tidy Backend

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#2169]
These are some minor changes we should make to the existing backend before it is replaced by the new backend.

The purpose of these changes is to make the generated code independent of (1) the Flix compiler and (2) the flix-runtime.jar.

- [x] #2170
- [x] #2171
- [x] #2172
- [x] #2173
- [x] #2174
- [x] #2175
- [x] #1654
- [x] #2270
- [x] #2271
- [x] Re-implement channels in Flix. See in particular #1724 and #1840. I suggest to take #1904 as a starting point and break it down into the following sub-tasks
  - [x] #2176
  - [x] Backend: Concurrency: Implement a CyclicBuffer (Maybe #2031 can be used?)
  - [x] #2177
  - [x] #2178
  - [ ] Backend: Concurrency: Implement the Channel namespace using #1904.
  - [ ] Backend: Concurrency: Implement a Lowering phase to the Channel namespace.
  - [ ] Backend: Concurrency: Remove old, unused code.

**These changes should be kept minimal and independent of the new backend.**

**Comment by justinfargnoli** [comment]
I created issue #2221 for the "Backend: Concurrency: Implement a CyclicBuffer (Maybe Add MutDeque #2031 can be used?)" checkbox.

**Comment by justinfargnoli** [comment]
@magnus-madsen are #2177 and #2178 saying introduce a Flix namespace into the Flix standard library where all of the functions are just wrappers to the Java methods of the `ReenterantLock` and `Condition` type?

**Comment by magnus-madsen** [comment]
> 
> 
> @magnus-madsen are #2177 and #2178 saying introduce a Flix namespace into the Flix standard library where all of the functions are just wrappers to the Java methods of the `ReenterantLock` and `Condition` type?

Yes

**Comment by JonathanStarup** [comment]
@magnus-madsen maybe just close this?
