### ISSUE TITLE
Roadmap to disallowing non-unit expressions in statements and adding discard

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#3771]
* [x] Add the discard keyword #3673.
    * [x] Use the discard keyword #3984.
* [x] Make channel retrieval return unit #3683.
    * [x] Simplify parser to disallow chained <- operations #4093.
* [x] Make channel operations return unit in the new standard lib implementation #3775.
    * [x] #3880
* Remove non-unit statement expressions in standard library.
    * [x] #3877
    * [x] #3879
    * [x] #3882
* There are changes that are not needed but do support this design decision.
    * [x] Some functions want to use zipWithIndex for array, chain, delaylist, nec but use a fold instead #3682.
        * Rewrite some folds to use zipWithIndex and foreach instead of folds
            * [x] #3881.
            * [x] #3878
    * [x] Add the fluent builder operator to remove return values on destructive methods #3664 and #3694.
        * [x] #3883
* [x] Add the redundancy check to disallow non-unit statement expressions #3667.

Issues related to this:
* #2432
    * A question for this is: should we add an ignore function to preamble? This would allow `something |> doSomething |> ignore`

**Comment by JonathanStarup** [comment]
@magnus-madsen I think this should capture all of the discussion around the topic and lay out the steps needed
