### ISSUE TITLE
Interoperability: Add an expression that allows the (anon.) implementation of a Java interface/class extension

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3888]
# Overall Goal: Add new anonymous class/object expression

For example:

```
object ##java.lang.Iterator {
  def hasNext(): Bool = true
  def next(): String = "Hello"
}
```

which will generate a new class called say `Anon$1` which implements the `Iterator` interface and has two methods `hasNext` and `next`. The `object` expression is a Java value of type `##java.lang.Iterator`. (We ignore generics for now-- they are erased anyway.)

I propose to work towards this goal through several milestones:

# Milestone 1

- [ ] Add a new ` NewObject` expression (right after PutStaticField) that takes a list of `1` class and `n` interfaces. 

For example, we should be able to compile and run these expressions (trivial as they may be):

Ex1:
```
object ##java.lang.Object {  }
```

Ex2:
```
object ##java.lang.Serializable {  }
```

Ex3:
```
object ##java.lang.Object, ##java.lang.Serializable, ##java.util.RandomAccess {  }
```

# Milestone 2

TBD

**Comment by mlutze** [comment]
How about `object` for the keyword? Too confusing wrt Scala?

**Comment by magnus-madsen** [comment]
> How about `object` for the keyword? Too confusing wrt Scala?

Could work.

**Comment by JonathanStarup** [comment]
maybe implement, like `implement ##java.lang...`.

also, its only java classes here right? so maybe no ##

**Comment by paulbutcher** [comment]
For reference, this is how Clojure does it (which is very nice and simple):

https://clojure.org/reference/java_interop#_implementing_interfaces_and_extending_classes

**Comment by paulbutcher** [comment]
(makes it very clear that what's going on is very different from Java's `extend`.

**Comment by magnus-madsen** [comment]
@paulbutcher I wrote a first proposal. Very simple, but would still require a principled restructuring throughout the compiler.

**Comment by paulbutcher** [comment]
It is very simple 👍

Playing devil's advocate: What are the use cases where we would want to create an object that implements more than one interface or extends a single class without any interfaces?

The vast majority of cases I can think of would only require a single interface (and in the rare case where you might need to implement more than one, you could always implement a class in Java which implements the interfaces you're interested in, and then extend that class?).

I don't know whether that would make things simpler? But if it would, perhaps worth considering?

**Comment by magnus-madsen** [comment]
> The vast majority of cases I can think of would only require a single interface (and in the rare case where you might need to implement more than one, you could always implement a class in Java which implements the interfaces you're interested in, and then extend that class?).

Agreed. We can start with one interface/abstract class/class 👍

**Comment by magnus-madsen** [comment]
I think the first PR should be:

- [ ] Extend `ParsedAst.Expression` with a new case class `NewObject(sp1: SourcePosition, fqn: Seq[String], sp2: SourcePosition)`. This should be added right after "LetImport" in the list of case classes and in pattern matches.
- [ ] Add parsing for `object ##java.lang.Iterator { }`
- [ ] Continue through the ASTs and phases: WeededAst/Weeder, NamedAst/Namer, ResolvedAst/Resolver, KindedAst/Kinder. Most phases should be straightforward: Just recursive calls mostly. 

The next PR could then be the Typer.

The PR after that would be the rest of the (many) compiler phases with the backend being the only difficult one. @JonathanStarup Will be able to help.

**Comment by paulbutcher** [comment]
To check I'm understanding, the first PR would enable me to add a test along the following lines (in a file called `Test.Exp.Jvm.Object.flix`):

```
namespace Test/Exp/Jvm/Object {

  @test
  def testImplementInterface01(): Bool & Impure =
    let it = object ##flix.test.TestInterface { };
    true
}
```

Yes?

And then subsequent PRs would enable the innards of that test to be filled out?

**Comment by magnus-madsen** [comment]
Yep. Pretty much.

**Comment by magnus-madsen** [comment]
I suggest you create the PR immediately after doing a couple of phases -- even when very incomplete.

**Comment by magnus-madsen** [comment]
That's the best way to get early feedback and to discover potential issues.

**Comment by magnus-madsen** [comment]
In fact, writing a few test cases could also be a useful start.

**Comment by paulbutcher** [comment]
Completely agree that writing tests would be the best starting point. Not least because thinking about the tests leads me to think about questions like how we plan to handle arguments to a superclass constructor within this scheme?

Something like this?: 

```
object ##flix.test.TestClass(... superclass constructor arguments ...) {
    ...
}
```

Or, possibly, given that we're only doing this for interoperability, and in the vast majority of cases that will mean implementing interfaces, do we need to worry about objects/abstract objects at all, which will enable us to avoid this wrinkle?

**Comment by magnus-madsen** [comment]
> Completely agree that writing tests would be the best starting point. Not least because thinking about the tests leads me to think about questions like how we plan to handle arguments to a superclass constructor within this scheme?
> 
> Something like this?:
> 
> ```
> object ##flix.test.TestClass(... superclass constructor arguments ...) {
>     ...
> }
> ```
> 
> Or, possibly, given that we're only doing this for interoperability, and in the vast majority of cases that will mean implementing interfaces, do we need to worry about classes/abstract classes at all, which will enable us to avoid this wrinkle?

I think we should deal with constructor arguments in "iteration 3". I think "iteration 1" would be just empty objects. "Iteration 2 would be implementing methods for interfaces (which cannot have constructors). Then we get to the constructors.

**Comment by paulbutcher** [comment]
> I think we should deal with constructor arguments in "iteration 3". I think "iteration 1" would be just empty objects. "Iteration 2 would be implementing methods for interfaces (which cannot have constructors). Then we get to the constructors.

Agree with that. But I do want to make sure that whatever syntax we come up with is capable of being extended to handle things like calling superclass constructors? I guess there are enough options we're unlikely to paint ourselves into a corner though, so I'll stop worrying.

**Comment by paulbutcher** [comment]
So to get code generation working, how close am I with:

1. Add `freshObjectSym` to `Symbol`
1. Add a `sym` field to `NewObject` and populated it in `Namer`
1. Add a new `newObjectsOf` method to `JvmOps` which will take `root` and return a set of `NewObject`s
1. Add something like this to `JvmBackend.run`:
```
val newObjects = JvmOps.anonClassesOf(root)
...
val anonClasses = GenAnonClasses.gen(newObjects)
```
5. Create `GenAnonClasses` and name the class using the symbol
6. Modify the `NewOject` case within `GenExpression` to `INVOKESPECIAL` that class's `<init>` method.

**Comment by paulbutcher** [comment]
I guess step 3 is the step which you felt might be usefully pulled into an earlier phase? Which makes sense: it would avoid walking the AST again.

**Comment by paulbutcher** [comment]
> start with a single hard coded name

That makes sense

**Comment by magnus-madsen** [comment]
I think my ideal steps would be:

- Step 4 to 6. (I do like TDDs "take small steps").
- Introduce Symbol.JvmClassSym (I think `NewObject` or `ObjectSym` etc is too vague).
- Refactor Namer to use JvmClassSym (and refactor every subsequent phase to use it).
- Collect all JvmClassSyms and generate classes for them. (Later we can try to be smarter).

**Comment by paulbutcher** [comment]
While I'm looking at this code, I notice that `JvmOps.tagsOf` calls `JvmOps.typesOf`, walking the entire AST again. Can we rejig this so that it takes the results of `typesOf` as an argument instead of `root` to avoid the unnecessary repeated work?

**Comment by JonathanStarup** [comment]
It is to plan to do these all at once (maybe in the eraser phase? or even a self-contained one) and collect all the different types needed for code generation. I think there's also a comment to that effect in JvmBackend

**Comment by paulbutcher** [comment]
> It is to plan to do these all at once (maybe in the eraser phase? or even a self-contained one) and collect all the different types needed for code generation. I think there's also a comment to that effect in JvmBackend

Indeed. I'm wondering whether it makes sense for me to do that before making the problem worse?

**Comment by magnus-madsen** [comment]
I think it's okay to make the problem worse. Mostly because that code can easily be removed again. The bigger question is how to do this nicely. But I think for anon classes it would mean to lift them into a map at some point. Probably around lambda lifting.

**Comment by magnus-madsen** [comment]
So I propose the ugly duplicate code. Then we get something that works with new object. Then we refactor by introducing anon class sym or whatever.

**Comment by magnus-madsen** [comment]
I think we can introduce the symbol after or during `LambdaLifting`. Ill sketch at plan later.

**Comment by magnus-madsen** [comment]
Beginning of a plan:

- [ ] Extend `NewObject` with a `List[JavaMethod]`
- [ ] Add `case class JavaMethod(sp1: ..., ident: Name.Ident, fparams: Seq[ParsedAst.FormalParam], exp: ParsedAst.Expression, tpe: ParsedAst.Type, sp2: ...)` to `ParsedAst` (Add it after the `object Jvm`)
- [ ] Extend the parser to allow a sequence of `JavaMethod`s in the body of `NewObject`. Let's aim to support `def name(x: Int32): Int32 = exp` in the first iteration. We should be able to reuse several components of the Parser (e.g. parsing a list of formal parameters, parsing types, and expressions). 

Once `Parser` and `ParsedAst` is in place the subsequent phases will follow more naturally.

**Comment by paulbutcher** [comment]
Sounds good.

Any thoughts on how to name these objects? Without names, testing them is going to be pretty close to impossible.

**Comment by magnus-madsen** [comment]
Which objects do you mean?

**Comment by JonathanStarup** [comment]
> * [ ]  Add `case class JavaMethod(sp1: ..., ident: Name.Ident, fparams: Seq[ParsedAst.FormalParam], exp: ParsedAst.Expression, tpe: ParsedAst.Type, sp2: ...)` to `ParsedAst` (Add it after the `object Jvm`)
> * [ ]  Extend the parser to allow a sequence of `JavaMethod`s in the body of `NewObject`. Let's aim to support `def name(x: Int32): Int32 = exp` in the first iteration. We should be able to reuse several components of the Parser (e.g. parsing a list of formal parameters, parsing types, and expressions)`

Could they not just be a LetRecDef? the object Ast node would then at some point be a list of closures

**Comment by magnus-madsen** [comment]
I have an intermediate solution: Can we use the source location to get the current filename and line number?

(The real solution; to arrive later, is to have some notion of symbols.)

**Comment by magnus-madsen** [comment]
(I actually think this problem will be solved naturally once we do the refactor above and arrive at the Lambda Lifting phase).

**Comment by paulbutcher** [comment]
Sounds good - I'll get that done ASAP and then move on to your suggestions above.

**Comment by paulbutcher** [comment]
I think that this is close-able now?

**Comment by magnus-madsen** [comment]
Yes, but I will create a ticket about polishing :)
