### ISSUE TITLE
Towards a stateful REPL

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4044]
# Goals
- Allow the user to define "local variables" and interact with them (notebook-style, if you will).
- Do not break the compiler architecture. 

We want to support this:

```
flix> let x = 123;
<That's an Int32!>
flix> x + 1
124
```

# Milestones: 
- [ ] Extend `Shell` with a mutable type environment and a mutable value environment (of the form `Map[String, AnyRef]` and `Map[String, Type]`. Both environments must be cleared when the program is reloaded or a new declarations is added.
- [ ] Allow the user to type exactly `let s = 42` where `s` is any string (that is valid as an identifier) and extend the value and type environments appropriately. 
- [ ] Modify the compiler and ASTs to carry along an "Open Expression" together with the type environment. (We need to figure out a few things: How do we perform naming on this expression? Do we wrap it in a function? How do we compile it?) 
- [ ] Retrieve a `Method` object from `CompilationResult` and reflectively invoke it with the value environment. (Perhaps we need to number them?) 

# Questions:
- Can we transform the local let-bindings as arguments? A JVM method cannot accept more than 255 arguments which means that after 255 we would run out. (Unless we try to do something more complicated...).

**Comment by paulbutcher** [comment]
@magnus-madsen, I'm looking at this, and I think I understand the motivation behind most of it. The bit I'm not sure about is:

>Modify the compiler and ASTs to carry along an "Open Expression" together with the type environment. (We need to figure out a few things: How do we perform naming on this expression? Do we wrap it in a function? How do we compile it?)

Are you thinking that this will be a single "open expression" that carries over from one line typed at the REPL to the next? Or are you talking about within a single compiler invocation? Can you help me understand what you have in mind here?

**Comment by magnus-madsen** [comment]
> @magnus-madsen, I'm looking at this, and I think I understand the motivation behind most of it. The bit I'm not sure about is:
> 
> > Modify the compiler and ASTs to carry along an "Open Expression" together with the type environment. (We need to figure out a few things: How do we perform naming on this expression? Do we wrap it in a function? How do we compile it?)
> 
> Are you thinking that this will be a single "open expression" that carries over from one line typed at the REPL to the next? Or are you talking about within a single compiler invocation? Can you help me understand what you have in mind here?

This has a technical meaning: It means an expression that has free (unbound) variables.

**Comment by paulbutcher** [comment]
Gotcha. So this is within a single compiler invocation (which makes sense). Great.

Are you happy for me to start working my way through this?

**Comment by magnus-madsen** [comment]
> Gotcha. So this is within a single compiler invocation (which makes sense). Great.
> 
> Are you happy for me to start working my way through this?

I think you can do the parts that belong to the shell (milestones 1-3), but for the compiler, we need to figure out a detailed plan of what to do.

**Comment by paulbutcher** [comment]
@magnus-madsen, re:

> Both environments must be cleared when the program is reloaded or a new declarations is added.

I understand why the environments should both be cleared when the program is reloaded. Can you help me understand why they would need clearing when a new declaration is added?

**Comment by magnus-madsen** [comment]
> @magnus-madsen, re:
> 
> > Both environments must be cleared when the program is reloaded or a new declarations is added.
> 
> I understand why the environments should both be cleared when the program is reloaded. Can you help me understand why they would need clearing when a new declaration is added?

Let me think. Its been a while. I think the concern is incompatible re-declarations, but I am not 100% sure. But possibly this is not necessary.

**Comment by paulbutcher** [comment]
@magnus-madsen, related to the above, can you explain this code to me:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/runtime/shell/Category.scala#L53

The way that it's written implies that there are occasions where a code fragment could *both* parse as a declaration, *and* parse as an expression? But I can't immediately think of an occasion where this could happen in practice? Can you enlighten me?

**Comment by magnus-madsen** [comment]
I think a def could be both. It might also be a bit of future proofing.

**Comment by paulbutcher** [comment]
As part of looking at this, I think I need to revisit the creation of string representations for types that don't implement `ToString` as discussed in #2769.

[This comment](https://github.com/flix/flix/issues/2769#issuecomment-985354107) suggests that there is an issue with string representations for tuples with more than 10 elements, but in the experiments I've done, I've successfully printed out tuples with much more than 10 elements, e.g. this compiles and creates exactly what I would expect:

```
def main(): Unit \ IO =
    println(("one", 2, 3.0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14))
```

Is this something that's changed since #2769 was created? Or is the comment referring to something else relating to "large" tuples?

**Comment by paulbutcher** [comment]
To answer my own question, it looks like the limit was increased to 15 in #1891

**Comment by paulbutcher** [comment]
@magnus-madsen, I've been looking at this, and I fear that we might some more thinking before going ahead.

I was pleasantly surprised to discover that this already works:

```
flix> let x = 1; x + 1
2
```

Which is great. But then it leads to an interesting question about what the behaviour of `let`s within an expression (as opposed to "bare") should do. So this:

```
let x = 1
```

Should presumably leave us with `x` defined and with the value `1`. But should the code above do the same? What if the user types something like:

```
let x = 1; let y = x + 1
```

Should that leave us with `x` set to `1` and `y` set to `2`? Or should it just leave us with `y` set to `2`? Or should it be an error? Or...?

It strikes me that we have four choices, but it's not clear to me which choice is the most palatable:

1. Every `let` typed within the REPL defines a new top-level variable, visible for the remainder of the REPL session (or until reload).
2. Only "bare" `let`s are allowed to define top-level variables.
3. Only "free" `lets` (those that aren't used within their expression) define top-level variables.
4. We have some other syntax for defining top-level variables to avoid it being confused with `let`. I would suggest `let*` but that's already taken 😜. Perhaps `var`?

Or some other option?

**Comment by paulbutcher** [comment]
Perhaps `:let` to make it clear that it's a REPL-only thing?

**Comment by magnus-madsen** [comment]
I think let should be treated separately. So I would go with 1. I think that's the standard in other REPLs.

**Comment by paulbutcher** [comment]
> I think let should be treated separately. So I would go with 1. I think that's the standard in other REPLs.

Just to make sure that we're talking about the same thing, what I intended by option 1 above was that:

```
let x = 1; let y = x + 1; y
```

Would both print `2` and result in two new top-level bindings being added: `x` ← `1` and `y` ← `2`. And, by extension:

```
let x = 1; let y = x + 1
```

Would be legal, return nothing (unit) and result in the same two top-level bindings.

Is that what you intended?

The more I think about it, the more I'm in favour of `:let` to define top-level bindings in the REPL:

* I wouldn't worry too much about what "other REPLs" do here. Flix is very different from any other language I'm aware of in that it doesn't allow top-level variables, so it wouldn't be either surprising or wrong for Flix to do something different when it comes to top-level variables in the REPL.
* This behaviour is definitely REPL-only (we aren't planning to add top-level variables to the language), so a syntax that makes it clear that it's REPL-only makes sense to me?
