### ISSUE TITLE
Ast-Printer

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#5160]
### AST Printer

I think Flix should allow the programmer to see any intermediate representation of their code to
1. Understand and explore Flix
2. Debug code for compilation errors (for compiler devs)
3. Debug code and tests for runtime errors (for compiler devs)
4. Optimize code
5. Might allow "reformat code" in VSCode

For point 2, this process mustn't require the full compiler to run but only the phases leading up to the desired AST. For point 3, the identifiers in the printout must be consistent with runtime identifiers.

---

### API

I imagine that you can set an AST-print flag, `--Xprint-asts <phase>,<phase>,...,<phase>` where
- `<phase>`: is a name `parsedAST` of a phase

This will be output to `./build/asts/<phase>.flixir`

It must be a flag instead of a command for use case 3. If you want your AST and nothing else, then you can use `check` along with the `print-ast` flag.

### What do we print?

- ~Everything? (Could be quite big)~
- ~Only defs from a specific namespace?~
- Only defs from a specific file?
- ~A single def and all its dependencies?~

This is also a question of where to put the button in Vscode. Depending on the choice here, additional args to the flag might be needed.

---

### Task list

- [x] Pretty Printer library (https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf)
    * #5161
- [x] Pretty Printer common AST & type formatting
   * #5161
- [ ] Pretty print each AST and type format
    - [X] Eraser
    - [X] Finalize
    - [X] LambdaLift
    - [X] MonoType
    - [ ] Type
    - [ ] ...
- [ ] Add compiler flag and customization
    - [X] flag
    - [ ] customization
- [x] #5898
    - [ ] vscode
    - [ ] CLI
- [ ] Merge LSP formatting 
- [ ] Add Vscode action to show ASTs
    * https://github.com/flix/vscode-flix/pull/255
    * https://github.com/flix/flix/pull/5565
    - [ ] filter to file/mod/def

**Comment by magnus-madsen** [comment]
I will ask Magnus to add a "Show TypedAst" button to VSCode.
