### ISSUE TITLE
Package Manager - Milestones

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5196]
I think its time to push forward on package management, so I made some decisions. I hope they are agreeable. 

Ultimately, from a programmers point-of-view, I think we get everything that has been discussed. It is only on the implementation side that I made some more controversial choices [1] which boil down to: (1) keep it in Scala and (2) keep it in one jar.

I propose the following milestones (many of which can be worked on concurrently):

Milestone 0: Preliminaries (Matt and Magnus)
- [ ] Rework `Main.scala` to have a clear control-flow. We probably want to sketch it out on paper.

Milestone 1: TOML
- [ ] Add support for reading and writing `flix.toml` files. Include a dependency on https://github.com/tomlj/tomlj.
- [ ] Define Scala data types that correspond to the content of the TOML file. 
- [ ] We should have a **one** class that can read and write `flix.toml`. This class should not have any dependencies on Flix itself.
- [ ] Put all of this into a new package in `flix/tools/packagemgmt/XYZ` (or similar).

Milestone 2: Flix Packages
- [ ] Add support for dependency resolution of Flix packages.

Milestone 3: Maven Packages
- [ ] Add support for dependency resolution of maven packages. (Yes, this means to include a lot of additional jars, but so be it).
- [ ] Investigate more closely exactly what jars are needed (e.g. I don't think we need two versions of asmweb).

Milestone 4: Connect the pieces
- [ ] Carefully modify `Main.scala` to call the above infrastructure.
- [ ] Define some data types to exchange information between the above components and the Flix compiler.

Milestone 5: Bootstrap (Assumes milestone 0 has been completed)
- [ ] Carefully modify `Main.scala` such that it reads `flix.toml`, fetches the `flix-version`, and compares it to its own version.
- [ ] If too old then look for `flix-v1.2.3.jar` in current folder. Download it if it does not exist.
- [ ] Fork the JVM to execute `flix-v1.2.3.jar`. 

Milestone 6: Cleanup
- [ ] Remove `Packager.flix` (unless it has been reworked into some of the above).

Once all of this is up and running, I am open to iteration and refinement.

[1] I think it is a important to write real programs in Flix, but I don't want to complicate the compiler with a Flix dependency at this point in time. I think efforts like writing https://api.flix.dev and many libraries (e.g. a webserver) are the right targets today.

**Comment by paulbutcher** [comment]
A few comments:

Re "Add support for dependency resolution of Flix packages."

Before we do that, I think we need to create the machinery to build and publish Flix packages? It won't add *much* to the current `fpkg` format, but as a minimum it needs to add the TOML file and allow transitive dependencies to be determined. Plus we'll need the machinery to download from GitHub.

I suggest that we switch the order of milestone 2 and 3. Milestone 3 is dramatically (at least an order of magnitude) less work than milestone 2: little more than plumbing in existing libraries.

Re: "Investigate more closely exactly what jars are needed (e.g. I don't think we need two versions of asmweb)." I assume that you're mentioning asmweb because it's included in https://github.com/paulbutcher/package-playground? I don't think you need to worry about it: this is only because I was forced to manage dependencies manually (which is toxic mix of time consuming, soul destroying, and error prone) and because asmweb isn't included within Flix. This will be much (much!) easier to manage through Gradle's built-in (via Maven) dependency management. And probably moot if we use Coursier instead of Maven.

Re: "If too old then look for flix-v1.2.3.jar in current folder. Download it if it does not exist."

This suggests that:

* We manage downloading `flix.jar` ourselves
* It should live in the current directory of each project

I strongly suggest that we do neither of the above. We can use a local JAR if one happens to be present (this might be useful during development) but:

* we're integrating with Maven, and what Maven *does* is download JAR files. We should leverage it and not write this functionality ourselves.
* We should not duplicate `flix.jar` for each project: it should live centrally (i.e. in the local Maven repo). If I have 10 different Flix projects, I do not want 10 copies of `flix.jar`.

Things which are missing from this ticket (and I think should be added):

* A command line wrapper (i.e. to allow the user to type `flix ...` instead of `java -jar flix.jar ...`
* A means for installing the above (probably via Homebrew for OSX/Linux and winget for Windows)

**Comment by paulbutcher** [comment]
@magnus-madsen, sorry to nag, but do you have any thoughts on my comment above?

**Comment by magnus-madsen** [comment]
- Agree with machinery for GitHub API integration.
- We can swap milestone 2 and 3 (I already considered them unordered or concurrent)
- OK on the Gradle dependencies. 

I think we disagree on distribution method, but maybe we should defer that: The question is, once you have Flix, how do you write TOML files, grab maven dependencies, and Flix dependencies.

**Comment by paulbutcher** [comment]
> I think we disagree on distribution method, 

Can I make sure I understand what you mean by "distribution method"? Are you referring to:

* The means by which `flix.jar` is downloaded?
* The means by which a command line `flix` command is installed?
* something else?

**Comment by magnus-madsen** [comment]
> > I think we disagree on distribution method,
> 
> Can I make sure I understand what you mean by "distribution method"? Are you referring to:
> 
>     * The means by which `flix.jar` is downloaded?
> 
>     * The means by which a command line `flix` command is installed?
> 
>     * something else?

Yes both of the above.

**Comment by magnus-madsen** [comment]
More or less, but:

- I am not against having an "official script(s)" as long as its optional.
- I am not against Debian/Ubuntu/Brew/Arch shipping flix with whatever script/setup they want.
- I am inclined to have an MSI installer for windows.
- I am against "install this maven stuff to install flix". What I mean is; if someone asks me to use tool W to get started with but I really just want to play with X, then I should not forced to learn W before X. (Substitute W for maven/gradle/sbt). My vivid nightmare is thinking JavaFX was cool then never being able to get the damn thing to run.
- I want _world-class_ VSCode support out-of-the-box with zero installation friction. 

I don't think there should be a `flix.jar` in every project, but I do think if there is one, then everything must work 100% using that.

**Comment by paulbutcher** [comment]
Ah! I think I see the misunderstanding. I think you are thinking that I'm suggesting that the programmer will need to install and interact with the Maven command line and/or repository in order to use Flix?

That is absolutely not what I'm suggesting (and I agree that if it was what I was suggesting, it would be a massive mistake). But we definitely don't need to do that.

I believe that we can kill all your birds with one stone, i.e.:

* We can avoid turning off people who hate Maven (they will be completely unaware that Maven in used: it will be entirely behind the scenes)
* We can avoid turning off people who like Maven (it will be used behind the scenes, and they can interact with it in the way that they're used to if they choose to)
* We can give people who like writing `flix foo.flix` something that works, trivially, out of the box.
* Script/classpath hell can be very easily avoided

I really don't think that any of the above is difficult. The Clojure ecosystem has all of the above and it all "just works".

Regarding your specific points:

> I am not against having an "official script(s)" as long as its optional.

Agreed, with one major caveat: a command line script should be the default. Tell the average programmer in the street that they will have to download a jar file and type `java -jar flix.jar` and they will immediately switch off: we'll lose them before they even get started.

> I am not against Debian/Ubuntu/Brew/Arch shipping flix with whatever script/setup they want.

Agreed

> I am inclined to have an MSI installer for windows.

Ouch. This will be much more work than supporting winget, and much more difficult to maintain. MSI installers are the right choice for GUI applications, but not for command line apps.

> I am against "install this maven stuff to install flix". What I mean is; if someone asks me to use tool W to get started with but I really just want to play with X, then I should not forced to learn W before X. (Substitute W for maven/gradle/sbt). My vivid nightmare is thinking JavaFX was cool then never being able to get the damn thing to run.

Agreed, but as I hope I've convinced you above this absolutely isn't what I am suggesting.

> I want world-class VSCode support out-of-the-box with zero installation friction.

Agreed 100%. I believe everything I'm suggesting is consistent with this (in fact, will considerably improve this situation) because it will unify VSCode's view of the world and the command line's.

> I don't think there should be a flix.jar in every project, but I do think if there is one, then everything must work 100% using that.

Also agreed with one caveat:

I think what you were suggesting (please correct me if I've misunderstood) is that in the event that the TOML file specified a Flix version, then `flix.jar` should be downloaded to the project directory. Given that most projects *will* specify a Flix version, this de-facto means that every project will have its own `flix.jar`.

Given that Maven centralises dependencies, and we've agreed (I believe, again please correct me if I've misunderstood) that Flix library dependencies should be centralised, I think it would be a mistake for `flix.jar` to be the only exception.
