### ISSUE TITLE
Def representation renovation

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6113]
- [x] Defs should store their return type instead of their full type
  - [X] SimplifiedAst #6020
  - [x] LiftedAst & OccurrenceAst #6116
  - [x] ReducedAst #6130
  - [x] MonoTypedAst #6144
  - [x] ErasedAst #6146
- [x] Defs should store their purity as `Purity` and not a `Type`
  - [x] Fix monomorpher to guarantee simple purities 
  - [x] SimplifiedAst
  - [x] LiftedAst
  - [x] ReducedAst
  - [x] MonoTypedAst
  - [x] ErasedAst
- [X] Defs should differentiate captured and explicit arguments #6034
- [x] Fix DocAst to use proper return type #6207
- [ ] make DocAst use def purity
- [x] Fix nullary lambdas #6115
  - [ ] make them Nel ? 
- [x] use closure information in backend #6117
  - [ ] avoid using nonempty cparams list
    - [ ] with bool flags? #6118
  - [ ] Optimize non-capture closures that just call a function
