### ISSUE TITLE
A New Parser

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6208]
# Background material:

- Lexing: https://craftinginterpreters.com/scanning.html
- Parsing: https://matklad.github.io/2023/05/21/resilient-ll-parsing-tutorial.html

# Overview

## Phase 1: Lexer
- [ ] Define a new type `Token` for tokens. Each token needs name and most likely a position.
- [ ] Define a new class `Lexer` and attach it after `Reader`.
- [ ] Challenge 1: Keep track of source positions.
- [ ] Challenge 2: Lexing of comments and whitespace.
- [ ] Challenge 3: Support interpolated strings.
- [ ] Challenge 4: Support nested block comments. 
- [ ] Challenge 5: Support fault tolerance. 
- [ ] Goal 1: High-quality error reporting.
- [ ] Goal 2: Lexing of the Flix Standard Library.
- [ ] Goal 3: Lexing significantly faster than current `Parser`.

## Phase 2: Parser
- [ ] Introduce a new type `UnstructuredAst`.
- [ ] Define a new class `UnstructuredParser` and attach it after `Lexer`.
- [ ] Goal 1: Parse all of the Flix Standard Library.
- [ ] Goal 2: Lexing and Parsing has comparable performance to current `Parser`.

## Phase 6: Extend and Exploit Fault Tolerance

**Comment by magnus-madsen** [comment]
CC @herluf-ba

**Comment by LionelMeli** [comment]
Hello,

it's linked with this issue: [Upgrade to Scala 3 #6270](https://github.com/flix/flix/issues/6270), isn't it ?
Do you have in mind to rewrite the new parser directly in Flix ?

**Comment by magnus-madsen** [comment]
@LionelMeli Herluf is working on a new parser, currently.
