### ISSUE TITLE
HtmlDocumentor Checklist

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#6374]
Checklist:
- [x] All pages should produce valid HTML.
- [ ] CSS should be valid
- [x] All pages should render without JavaScript.
- [x] All pages should work locally (i.e. without internet).
- [x] All links should work.
- [x] Mobile should work.

**Comment by magnus-madsen** [comment]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fapi.flix.dev%2F

**Comment by magnus-madsen** [comment]
@sockmaster27 Looks good so far. A few things (other than the menu thing which is still a problem):

- I get a CSS warning.
- I think links to GitHub should have the "nofollow" tag-- this would also help link checkers.

Other than fixing these three things, are there any small tweaks or refactorings you want to do before we move on to the next thing?

(I plan to revisit the HtmlDocumenter-- but not for a few months while we work on other things and get ideas for how  to improve it).

**Comment by magnus-madsen** [comment]
@sockmaster27 Uhm.. Are the `source` links now broken??

**Comment by sockmaster27** [comment]
> * I get a CSS warning.

Where? I don't see anything?

**Comment by magnus-madsen** [comment]
It was just some online checker

**Comment by magnus-madsen** [comment]
https://jigsaw.w3.org/css-validator/validator?uri=api.flix.dev&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
