### ISSUE TITLE
Effect Handlers

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#6698]
What is needed for effect handlers to work (in the backend)? The filled dots indicate a mix between complexity and how cumbersome it is -- trying to estimate the relative hours it will take.
- [x] Bind resume as a variable (🔴🔴🔴⭕⭕) #6642
  - To use an effect class per effect, resume must be a regular variable.
- [x] Lambda lift handler bodies (🔴⭕⭕⭕⭕) #6708
- [x] Effect classes (🔴⭕⭕⭕⭕)  #6711
  - A Flix effect is a named set of defs, which will be a backend class with a field for each def, e.g., a `print` field that holds a `Fn1$Obj` def.
- [x] Add frame information to defs (🔴🔴⭕⭕⭕) #6738
  - find local variables #6725
  - add pc field
  - The frame holds local variable information (needed for resumption).
- [x] Add `pc` resumption points that load the resumption argument (🔴🔴🔴🔴⭕)
- [x] implement `TryWith` (🔴🔴⭕⭕⭕)
  - remember to Value wrap the result of the handler op closure 
- [x] implement `Do` (🔴⭕⭕⭕⭕)
- [x] implement `resume` (🔴⭕⭕⭕⭕)
  - materialize resume into a normal function (with Value boxing/unboxing)
