### ISSUE TITLE
Move and improve `TailRec`

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7183]
Current backend phases are shown below. It seems like we can simplify the phases following `TailRec` by moving it down after `Eraser`. This would removed the `TailX` ast node variants in `LiftedAst`.

Tail call information is used in `Optimizer` but only because it has to maintain this information, not because it uses it for anything.
 
| phase | type | AST input |
| ------ | ----- | --- |
| Lowering | Transformation ⚙️ | Typed |
| TreeShaker1 | Filtering 🔀 | Lowered |
| MonoDefs | Transformation ⚙️ | Lowered |
| MonoTypes | Transformation ⚙️ | Lowered |
| Simplifier | Transformation ⚙️ | Lowered |
| ClosureConv | Transformation ⚙️ | Simplified |
| LambdaLift | Transformation ⚙️ | Simplified |
| Tailrec | Information ℹ️ | Lifted |
| Optimizer | Transformation ⚙️ | Lifted |
| TreeShaker2 | Filtering 🔀 | Lifted |
| EffectBinder | Transformation ⚙️ | Lifted |
| Eraser | Lossy transformation ⚙️❕ | Reduced |
| Reducer | Information ℹ️ | Reduced |
| VarOffsets | Information ℹ️ | Reduced |
| JvmBackend | Lossy transformation ⚙️❕ | Reduced |

Todo list
- [x] Polish tailrec and add logic for letrec #7293
- [x] Move tailrec to just before the eraser (eraser wants to skip some work for tail position things) #7353
- [x] Rename CallType to ExpPosition (we want to track effect operations in tail position so need more general naming) #7376
- [x] Rename `Tailrec`, `TailPos` #7386
- [ ] Track ExpPosition for tryWith since we can skip effect call instrumentation  #7387

**Comment by magnus-madsen** [comment]
It is probably a good idea for tailrec to come very late, so yes I agree.

Although: Does the inliner use the information to avoid inlining recursive functions? Because that is always wasteful and must be avoided? Or does it have this information from some other source??

**Comment by JonathanStarup** [comment]
It doesnt check that currently no, but it seems it could still easily be added by carrying around the current symbol def

**Comment by magnus-madsen** [comment]
> It doesnt check that currently no, but it seems it could still easily be added by carrying around the current symbol def

Are you sure? I explicitly remember telling the group to be aware of that.

**Comment by magnus-madsen** [comment]
I see a check on line 138 in OccurrenceAnalyzer. So in other words, we should be good. We should be able to move tailrec later.

**Comment by JonathanStarup** [comment]
Oh, a complication:
- The backend needs to know up front how many resumption points a function has. This is `do` + `non-pure non-tail apply`.
- EffectBinder currently counts these points but with the tailrec move it doesn't know about tail position.
- If we move tailrec just before reducer, reducer could also count the resumption points.
- This would also be consistent with a future optimization where we only want to restore live local variables on effect operations, which would also need to happen in Reducer
