### ISSUE TITLE
clean up typereduction

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#8574]
- [x] editor reformat, unused variables, private defs, etc #8589
- [x] reorder functions in a logical order #8594
- [X] streamline (doc) comments  #8605
- [x] Remove todos #8689
- [ ] Collect jvm methods #8592

**Comment by mlutze** [comment]
Note that this is interacting with my current solver work, so please don't change the API for the moment.

**Comment by JonathanStarup** [comment]
it's just reformatting and doc comments. if the api is the same is it okay?

**Comment by mlutze** [comment]
> it's just reformatting and doc comments. if the api is the same is it okay?

Yes, that's fine

**Comment by magnus-madsen** [comment]
What are the tasks, I'm bullet point form?

**Comment by JonathanStarup** [comment]
Closing since only #8592 is left
