### ISSUE TITLE
Setification

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#8858]
When #8848 is merged, we will want to refactor many small parts of the compiler to properly deal with sets.

We need to:

- [x] #9186
- [X] Allow `main` to have subset of the base effects #9203 
- [x] Refactor monomorph to properly monomorphize concrete sets #9015
- [x] Refactor `Purity.fromType` to work correctly with sets #8918
- [X] Update `Safety` to correctly enforce that base effects cannot be handled #9090
- [X] Update ~`Safety`~ `Entrypoint` to correctly enforce that only base effects can be exported #9203 
- [x] Remove `TypeMinimization`
- [x] Refactor `SolverListener` to a trait #9156
- [x] Refactor all effects to have `handle` and `run` functions in their companion module
- [x] Remove old Boolean unification infrastructure (Magnus)
- [x] ~Enable TypeNormalization for Monomorph~ #9155
- [x] ~`case object InvalidType extends RuntimeException` - should be ICE~ #9171

**Comment by magnus-madsen** [comment]
What else?

**Comment by mlutze** [comment]
Figure out how sub-effecting works with typematch

**Comment by JonathanStarup** [comment]
> `case object InvalidType extends RuntimeException` - should be ICE

Why should this be type?

**Comment by magnus-madsen** [comment]
> > `case object InvalidType extends RuntimeException` - should be ICE
> 
> Why should this be type? `InvalidType` is like an AE exception. It's always handled

Good point. But I did not know that, and it was not documented! :)
